# Generated by Django 4.2.20 on 2025-04-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("content", models.TextField(blank=True, null=True, verbose_name="内容")),
                (
                    "keywords",
                    models.TextField(blank=True, null=True, verbose_name="关键词"),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("note", "笔记"),
                            ("tag", "标签"),
                            ("category", "分类"),
                            ("knowledge_node", "知识节点"),
                            ("transcription", "转录"),
                            ("community_post", "社区帖子"),
                            ("community_comment", "社区评论"),
                        ],
                        max_length=20,
                        verbose_name="索引类型",
                    ),
                ),
                ("object_id", models.CharField(max_length=50, verbose_name="对象ID")),
                (
                    "vector",
                    models.BinaryField(blank=True, null=True, verbose_name="向量表示"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "搜索索引",
                "verbose_name_plural": "搜索索引",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255, verbose_name="查询内容")),
                (
                    "search_type",
                    models.CharField(
                        default="text", max_length=20, verbose_name="搜索类型"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="过滤条件"),
                ),
                ("result_count", models.IntegerField(default=0, verbose_name="结果数量")),
                (
                    "execution_time",
                    models.FloatField(default=0, verbose_name="执行时间(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "搜索查询",
                "verbose_name_plural": "搜索查询",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("snippet", models.TextField(blank=True, null=True, verbose_name="摘要")),
                ("score", models.FloatField(default=0, verbose_name="相关度分数")),
                ("position", models.IntegerField(default=0, verbose_name="位置")),
                ("object_id", models.CharField(max_length=50, verbose_name="对象ID")),
                ("result_type", models.CharField(max_length=20, verbose_name="结果类型")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "搜索结果",
                "verbose_name_plural": "搜索结果",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="建议文本")),
                ("frequency", models.IntegerField(default=1, verbose_name="频率")),
                ("is_global", models.BooleanField(default=False, verbose_name="是否全局")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="最后使用时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "搜索建议",
                "verbose_name_plural": "搜索建议",
                "ordering": ["-frequency", "-last_used"],
            },
        ),
    ]
