# Generated by Django 4.2.20 on 2025-04-30 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsuggestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_suggestions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="searchresult",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="内容类型",
            ),
        ),
        migrations.AddField(
            model_name="searchresult",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="search.searchquery",
                verbose_name="查询",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_queries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="searchindex",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="内容类型",
            ),
        ),
        migrations.AddField(
            model_name="searchindex",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_indices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="searchsuggestion",
            index=models.Index(
                fields=["user", "frequency"], name="search_sear_user_id_e0b44a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchsuggestion",
            index=models.Index(
                fields=["is_global"], name="search_sear_is_glob_7d83cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchsuggestion",
            index=models.Index(fields=["text"], name="search_sear_text_17ebbc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="searchsuggestion",
            unique_together={("user", "text")},
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["query", "position"], name="search_sear_query_i_63e3d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="search_sear_content_aff08c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "created_at"], name="search_sear_user_id_2836be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["query"], name="search_sear_query_eedf16_idx"),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(
                fields=["user", "index_type"], name="search_sear_user_id_242f2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="search_sear_content_97a989_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(
                fields=["is_public"], name="search_sear_is_publ_e1f479_idx"
            ),
        ),
    ]
