# Generated by Django 4.2.20 on 2025-05-14 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="群组名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="群组描述"),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="群组头像"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组",
                "verbose_name_plural": "群组",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedScreen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("stream_url", models.CharField(max_length=255, verbose_name="流地址")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_screens",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_screens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分享者",
                    ),
                ),
            ],
            options={
                "verbose_name": "共享屏幕",
                "verbose_name_plural": "共享屏幕",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="邀请消息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被邀请人",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组邀请",
                "verbose_name_plural": "群组邀请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("member", "成员")],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="群内昵称"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="加入时间"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组成员",
                "verbose_name_plural": "群组成员",
                "ordering": ["group", "joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
