# Generated by Django 5.2 on 2025-04-24 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=50, verbose_name='内容ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='内容类型')),
                ('reporter_id', models.CharField(max_length=50, verbose_name='举报者ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾信息'), ('inappropriate', '不当内容'), ('copyright', '版权问题'), ('other', '其他')], max_length=20, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='举报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内容举报',
                'verbose_name_plural': '内容举报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '笔记分类',
                'verbose_name_plural': '笔记分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
    ]
