"""
Django settings for admin_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)^7v^)tzs6exa4)0@75cw5pa%0cq7&y_recb78u&7j(i#ul7!$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方应用
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # 自定义应用
    'auth_api',
    'users',
    'content',
    'settings_api',
    'logs',
    'sync',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',  # 使用dummy引擎，因为我们使用mongoengine
    }
}

# MongoDB设置
import mongoengine
import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# 连接到主软件的MongoDB数据库
MONGO_HOST = os.environ.get('MONGO_HOST', 'localhost')
MONGO_PORT = int(os.environ.get('MONGO_PORT', 27017))
MONGO_DB = os.environ.get('MONGO_DB', 'zeroislenotes')
MONGO_USER = os.environ.get('MONGO_USER', '')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', '')

# 连接到MongoDB
if MONGO_USER and MONGO_PASSWORD:
    mongoengine.connect(
        db=MONGO_DB,
        host=MONGO_HOST,
        port=MONGO_PORT,
        username=MONGO_USER,
        password=MONGO_PASSWORD,
        authentication_source='admin'
    )
else:
    mongoengine.connect(
        db=MONGO_DB,
        host=MONGO_HOST,
        port=MONGO_PORT
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework 配置
#
# 认证类说明（方案 B）：
# 原先用 DRF 自带的 SimpleJWT 认证，其 get_user 走 Django ORM，
# 而本项目的数据库引擎是 dummy（见上方 DATABASES），因此认证必然失败。
# 现改用 auth_api.authentication.AdminJWTAuthentication：
# 它同样基于 SimpleJWT 校验令牌，但把用户解析到 MongoDB 的 users 集合，
# 并要求 is_staff=True —— 与主后端的身份口径一致。
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth_api.authentication.AdminJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 改用自建分页类：同时接受 page_size 与 pageSize（前端用小驼峰），
    # 并约束最大页大小。详见 common/filters.py 的说明。
    'DEFAULT_PAGINATION_CLASS': 'common.filters.MongoPageNumberPagination',
    'PAGE_SIZE': 10
}

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

# CORS 配置
#
# 安全加固（本轮）：原先无条件 CORS_ALLOW_ALL_ORIGINS = True，
# 配合 CORS_ALLOW_CREDENTIALS = True，任何站点都能带凭据调用管理后台接口。
# 现在改为：由环境变量 ADMIN_CORS_ALLOWED_ORIGINS 显式声明允许来源；
# 未声明时按"仅本机开发来源"处理，而不是放开一切。
# 若确需在开发期放开，可显式设置 ADMIN_CORS_ALLOW_ALL=1（会打告警）。
_admin_cors_raw = os.environ.get("ADMIN_CORS_ALLOWED_ORIGINS", "").strip()
_admin_cors_origins = [o.strip() for o in _admin_cors_raw.split(",") if o.strip()]
_admin_cors_allow_all = os.environ.get("ADMIN_CORS_ALLOW_ALL", "") == "1"

if _admin_cors_allow_all:
    CORS_ALLOW_ALL_ORIGINS = True
    import logging as _logging

    _logging.getLogger(__name__).warning(
        "ADMIN_CORS_ALLOW_ALL=1：管理后台允许所有来源（仅限开发环境，切勿用于生产）"
    )
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _admin_cors_origins or [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

CORS_ALLOW_CREDENTIALS = True

# IP 白名单：让 .env.example 里长期存在但从未生效的 ADMIN_ALLOWLIST_IPS 真正起作用
# （中间件在未配置时不拦截，但会打 WARNING；生产应显式配置）
MIDDLEWARE.insert(
    MIDDLEWARE.index("django.middleware.security.SecurityMiddleware") + 1,
    "common.middleware.admin_ip_allowlist.AdminIPAllowlistMiddleware",
)

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
