# Generated by Django 5.2 on 2025-04-24 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=150, verbose_name='管理员用户名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('query', '查询'), ('export', '导出'), ('import', '导入'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='资源ID')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=20, verbose_name='日志级别')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
