# Generated by Django 5.2.5 on 2026-01-19 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0001_initial_task_model"),
    ]

    operations = [
        # migrations.RenameIndex operations removed due to AttributeError in test environment
    ]
