# Generated by Django 3.2.18 on 2025-04-27 08:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否验证')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('preferences', models.JSONField(default=dict, verbose_name='偏好设置')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='尝试时间')),
            ],
            options={
                'verbose_name': '登录尝试',
                'verbose_name_plural': '登录尝试',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博'), ('github', 'GitHub'), ('google', 'Google'), ('apple', 'Apple')], max_length=20, verbose_name='提供商')),
                ('uid', models.CharField(max_length=255, verbose_name='第三方用户ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新令牌')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '第三方账号',
                'verbose_name_plural': '第三方账号',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='设备ID')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('desktop', '桌面端')], max_length=20, verbose_name='设备类型')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='设备名称')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='操作系统版本')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='应用版本')),
                ('push_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='推送令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户设备',
                'verbose_name_plural': '用户设备',
                'ordering': ['-last_login_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('bio_extended', models.TextField(blank=True, verbose_name='扩展简介')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='社交链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('system', '跟随系统')], default='system', max_length=10, verbose_name='主题')),
                ('font_size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=10, verbose_name='字体大小')),
                ('language', models.CharField(choices=[('zh-CN', '简体中文'), ('en-US', '英文')], default='zh-CN', max_length=10, verbose_name='语言')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('email_notification', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('auto_save', models.BooleanField(default=True, verbose_name='自动保存')),
                ('auto_save_interval', models.IntegerField(default=60, verbose_name='自动保存间隔(秒)')),
                ('offline_mode', models.BooleanField(default=False, verbose_name='离线模式')),
                ('handwriting_recognition_mode', models.CharField(default='realtime', max_length=20, verbose_name='手写识别模式')),
                ('ai_assistant_enabled', models.BooleanField(default=True, verbose_name='启用AI助手')),
                ('ai_assistant_model', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='AI助手模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('reset_password', '重置密码'), ('change_phone', '变更手机号'), ('change_email', '变更邮箱')], default='login', max_length=20, verbose_name='用途')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['phone', 'is_used'], name='users_verif_phone_838597_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'is_used'], name='users_verif_email_301b48_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['code', 'purpose'], name='users_verif_code_3f4fe3_idx'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='thirdpartyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'timestamp'], name='users_login_ip_addr_7c2b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'timestamp'], name='users_login_usernam_9b9158_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='users_userd_user_id_a5f926_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id'], name='users_userd_device__c17433_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['push_token'], name='users_userd_push_to_e31daa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='thirdpartyaccount',
            index=models.Index(fields=['user', 'provider'], name='users_third_user_id_2107b5_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdpartyaccount',
            index=models.Index(fields=['provider', 'uid'], name='users_third_provide_d8e660_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thirdpartyaccount',
            unique_together={('provider', 'uid')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
    ]
