# Generated by Django 4.2.20 on 2025-05-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qq_avatar",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="QQ头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wechat_avatar",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="微信头像"
            ),
        ),
    ]
