# Generated by Django 5.2.5 on 2026-02-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wechat", "微信"),
                            ("google", "Google"),
                            ("apple", "Apple"),
                            ("qq", "QQ"),
                            ("weibo", "微博"),
                        ],
                        max_length=30,
                        verbose_name="提供商",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(max_length=255, verbose_name="提供商用户ID"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "社交账号",
                "verbose_name_plural": "社交账号",
                "db_table": "users_socialaccount",
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="users_socia_user_id_7706a7_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="users_socia_provide_f3abb4_idx",
                    ),
                ],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
    ]
