# Generated by Django 5.2 on 2025-04-24 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('status', models.BooleanField(default=True, verbose_name='登录状态')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='消息')),
            ],
            options={
                'verbose_name': '管理员登录日志',
                'verbose_name_plural': '管理员登录日志',
                'ordering': ['-login_time'],
            },
        ),
    ]
